version: '2'
services:
  blogextractor:
    build: .
    image: edeas123/blogextractor:latest
    command: /usr/local/bin/uwsgi --ini /project/uwsgi.ini
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    labels:
      io.rancher.container.pull_image: always
      role: "webservice"
