version: '2'
services:
  web:
    image: edeas123/blogextractor:latest
    ports:
     - "80:80"
    labels:
      role: "webservice"
    command: /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
