version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: blogextractor:latest
    ports:
     - "80:80"
    labels:
      role: "webservice"
    command: /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
