version: '2'
services:
  blogextractor:
    image: edeas123/blogextractor:latest
    command: /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
    tty: true
    stdin_open: true
    ports:
      - "80:80"
    labels:
      io.rancher.container.pull_image: always
      role: "webservice"
    volumes:
      - log:/var/log