version: '3'
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: edeas123/blogextractor:latest
    command: /usr/local/bin/uwsgi --ini /project/uwsgi.ini
    ports:
      - 5000:5000
    environment:
      APP_ENV: docker
    tty: true
    stdin_open: true
    restart: unless-stopped
