version: '2'
services:
  web:
    scale: 2
    start_on_create: false
    health_check:
      port: 5000
      interval: 10000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreateOnQuorum
      recreate_on_quorum_strategy_config:
        quorum: 1
      healthy_threshold: 2
      response_timeout: 2000
    upgrade_strategy:
      start_first: true
  lb:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: web
        source_port: 80
        target_port: 5000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 5000
      unhealthy_threshold: 3
      interval: 2000
