version: 2
jobs:
  flake8_test:
    docker:
      - image: python:3.6.6-stretch
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            pip install tox
            tox -e flake8
  mypy_test:
    docker:
      - image: python:3.6.6-stretch
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Static Typing
          command: |
            pip install tox
            tox -e mypy
  unit_test:
    docker:
      - image: python:3.6.6-stretch
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Unit
          command: |
            pip install tox
            tox -e unit
  integration_test:
    docker:
      - image: python:3.6.6-stretch
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Integration
          command: |
            pip install tox
            tox -e integration
  deploy:
    docker:
      - image: docker:18.06-git
    working_directory: ~/project
    steps:
      - checkout
#      - run:
#          name: Build and Push to the TestPyPI
#          command: |
#            pip install setuptools
#            python setup.py sdist
#            pip install twine
#            twine upload --repository-url https://test.pypi.org/legacy/ dist/*
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to docker hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run:
          name: Build docker image
          command: docker build -t blogextractor .
      - run:
          name: Push docker image to docker hub
          command: |
            REVISION_TAG=$CIRCLE_SHA1
            docker tag blogextractor $DOCKER_HUB_USERNAME/blogextractor:latest
            docker push $DOCKER_HUB_USERNAME/blogextractor:latest

workflows:
  version: 2
  built_test_deploy:
    jobs:
      - flake8_test
      - mypy_test
      - unit_test
      - integration_test
      - deploy:
          context: edeas123
          filters:
            branches:
              only:
                - master
          requires:
            - flake8_test
            - mypy_test
            - unit_test
            - integration_test
