version: 2
jobs:
  flake8_test:
    docker:
      - image: python:3.6.6
    working_directory: ~/project
    steps:
      - checkout
      # this next run would not be necessary if you
      # include tox in your base image
      - run:
          name: Install Tox
          command: pip install tox==2.9.1
      - run:
          name: Linting
          command: tox -e flake8
  mypy_test:
    docker:
      - image: python:3.6.6
    working_directory: ~/project
    steps:
      - checkout
      # this next run would not be necessary if you
      # include tox in your base image
      - run:
          name: Install Tox
          command: pip install tox==2.9.1
      - run:
          name: Static Typing
          command: tox -e mypy
  integration_test:
    docker:
      - image: python:3.6.6
    working_directory: ~/project
    steps:
      - checkout
      # this next run would not be necessary if you
      # include tox in your base image
      - run:
          name: Install Tox
          command: pip install tox==2.9.1
      - run:
          name: Integration
          command: tox -e integration
  deploy:
    docker:
      - image: docker:18.06-git
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Login, Build and Push docker image
          command: deploy/build_push_docker_image.sh

workflows:
  version: 2
  built_test_deploy:
    jobs:
      - flake8_test
      - mypy_test
      - integration_test
      - deploy
          context: edeas123
          filters:
            branches:
              only:
                - master
          requires:
            - flake8_test
            - mypy_test
            - integration_test
