version: 2
jobs:
  flake8_test:
    docker:
      - image: edeas123/blogbase
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Linting
          command: tox -e flake8
  mypy_test:
    docker:
      - image: edeas123/blogbase
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Static Typing
          command: tox -e mypy
  integration_test:
    docker:
      - image: edeas123/blogbase
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Integration
          command: tox -e integration
  deploy:
    docker:
      - image: docker:18.06-git
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install CLI tools
          command: |
            apk --update add py-pip
#      - run:
#          name: Build and Push to the TestPyPI
#          command: |
#            pip install setuptools
#            python setup.py sdist
#            pip install twine
#            twine upload --repository-url https://test.pypi.org/legacy/ dist/*
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install CLI tools
          command: pip install awscli
      - run:
          name: Login to AWS ECR
          command: eval `aws ecr get-login --no-include-email`
      - run:
          name: Login to docker hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run:
          name: Build docker image
          command: docker build -t blogextractor .
      - run:
          name: Push docker image to AWS ECR
          command: |
            REVISION_TAG=$CIRCLE_SHA1
            docker tag blogextractor $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/blogextractor:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/blogextractor:latest
      - run:
          name: Push docker image to docker hub
          command: |
            REVISION_TAG=$CIRCLE_SHA1
            docker tag blogextractor $DOCKER_HUB_USERNAME/blogextractor:latest
            docker push $DOCKER_HUB_USERNAME/blogextractor:latest

workflows:
  version: 2
  built_test_deploy:
    jobs:
      - flake8_test
      - mypy_test
      - integration_test
      - deploy:
          context: edeas123
          filters:
            branches:
              only:
                - master
          requires:
            - flake8_test
            - mypy_test
            - integration_test
