version: 2
jobs:
  flake8_test:
    docker:
      - image: python:3.6.6
    steps:
      - checkout
      # this next two run would not be necessary if you
      # include tox in your base image
      - run:
          name: Install Tox
          command: pip install tox==2.9.1
      - run:
          name: Linting
          command: tox -e flake8
  mypy_test:
    docker:
      - image: python:3.6.6
    steps:
      - checkout
      # this next two run would not be necessary if you
      # include tox in your base image
      - run:
          name: Install Tox
          command: pip install tox==2.9.1
      - run:
          name: Static Typing
          command: tox -e mypy
  integration_test:
    docker:
      - image: python:3.6.6
    steps:
      - checkout
      # this next two run would not be necessary if you
      # include tox in your base image
      - run:
          name: Install Tox
          command: pip install tox==2.9.1
      - run:
          name: Integration
          command: tox -e integration
workflows:
  version: 2
  built_test_deploy:
    jobs:
      - flake8_test
      - mypy_test
      - integration_test
