version: 2
jobs:
  flake8_test:
    docker:
      - image: python:3.6.6
    working_directory: ~/project
    steps:
      - checkout
      # this next run would not be necessary if you
      # include tox in your base image
      - run:
          name: Install Tox
          command: pip install tox==2.9.1
      - run:
          name: Linting
          command: tox -e flake8
  mypy_test:
    docker:
      - image: python:3.6.6
    working_directory: ~/project
    steps:
      - checkout
      # this next run would not be necessary if you
      # include tox in your base image
      - run:
          name: Install Tox
          command: pip install tox==2.9.1
      - run:
          name: Static Typing
          command: tox -e mypy
  integration_test:
    docker:
      - image: python:3.6.6
    working_directory: ~/project
    steps:
      - checkout
      # this next run would not be necessary if you
      # include tox in your base image
      - run:
          name: Install Tox
          command: pip install tox==2.9.1
      - run:
          name: Integration
          command: tox -e integration
  deploy:
    docker:
      - image: docker:18.06-git
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install CLI tools
          command: pip install awscli
      - run:
          name: Login, Build and Push docker image to AWS ECR
          command: |
            eval `aws ecr get-login --no-include-email`
            docker build -t blogextractor .
            docker tag blogextractor $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/blogextractor:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/blogextractor:latest
      - run:
          name: Login, Build and Push docker image
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker build -t blogextractor .
            docker tag blogextractor $DOCKER_HUB_USERNAME/blogextractor:latest
            docker push $DOCKER_HUB_USERNAME/blogextractor:latest

workflows:
  version: 2
  built_test_deploy:
    jobs:
      - flake8_test
      - mypy_test
      - integration_test
      - deploy:
          context: edeas123
          filters:
            branches:
              only:
                - dev
          requires:
            - flake8_test
            - mypy_test
            - integration_test
